data = {1, "hello", 3.14, True, (5, 6)}

data.add("new item")
data.clear()
data = {1, "hello", 3.14, True, (5, 6)}
copy_data = data.copy()
data.discard("hello")
data.remove(3.14)
data.update({7, 8, 9})
popped_item = data.pop()
data.add("hello")
difference_set = data.difference({1, 7})
intersection_set = data.intersection({1, 8, 9, "hello"})
union_set = data.union({10, 11})
symmetric_difference_set = data.symmetric_difference({1, 9})
is_subset = {1}.issubset(data)
is_superset = data.issuperset({1})
is_disjoint = data.isdisjoint({2, 3})

print("Data:", data)
print("Copied Data:", copy_data)
print("Popped Item:", popped_item)
print("Difference Set:", difference_set)
print("Intersection Set:", intersection_set)
print("Union Set:", union_set)
print("Symmetric Difference Set:", symmetric_difference_set)
print("Is Subset:", is_subset)
print("Is Superset:", is_superset)
print("Is Disjoint:", is_disjoint)
